#
# في هذا الملف ستجد كل المتغيرات التي تتحكم في إعدادات المدونة، شخصّها على حسب متطلباتك
#

# اسم المدونة الذي سيظهر في الأعلى
name: سايبرسنشي Cybersenshi

# وصف قصير للمدونة والذي سيظهر تحت اسمها وكجزء من عنوان المدونة في محركات البحث
description: مدونة سايبرسنشي Cybersenshi لتبسيط و أتمتة و تسهيل أنشطة الأمن السيبراني للجميع

# رابط صورة المدونة
# لإستخدام صورة هويتك في GitHub ضع https://github.com/<اسم_المستخدم>.png في المتغير، مثلا لهويتي الشخصية أستخدم:
# avatar: https://github.com/a3ammar.png
# ولإخفاء الصورة نهائيًا احذف الرابط من المتغير
avatar: https://www.cybersenshi.com/icons/icon-512x512.png


#
# المتغيرات الآتية هي خيارية، عدل عليها إذا أردت تخصيص أكثر للمدونة
#

# لكل هوية تضعها هنا ستظهر أيقونة في أسفل المدونة
footer-links:
  email: info@cybersenshi.com
  rss: Cybersenshi.com
  twitter: thecybersenshi

# إذا أردت تفعيل إحصاءات الزوار في Google Analytics أدخل المعرف الخاص بك (مثلاً UA-2110908-2)
google_analytics: UA-142522483-1

# عنوان موقعك مثلاً http://barryclark.github.io
# يستخدم هذا المتغير في الـRSS والـSitemap.xml
url: blog.cybersenshi.com


#
# هذه المتغيرات خاصة بـJekyll ولا أنصح بتعديلها، لذلك لا حاجة لشرحها
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
